name: Pipeline CI/CD Cloud Run

on:
  push:
    branches:
      - master

env:
  SERVICE_NAME: ${{ github.event.repository.name }}
  REGION: us-central1
  
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Account
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          install_components: 'gke-gcloud-auth-plugin'

      - name: Configure Docker Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build Image
        run: docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} ./backend

      - name: Push Artifactory Registry
        run: docker push ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Crear archivo env-vars.yaml
        run: |
          echo "creating env-vars.yaml..."
          echo "env:" > env-vars.yaml
          grep -v '^#' .env | grep -v '^$' | while IFS='=' read -r key value; do
            clean_value=$(echo "$value" | sed -e 's/^"//' -e 's/"$//')
            if [ -n "$clean_value" ]; then
              echo "  $key: \"$clean_value\"" >> env-vars.yaml
            fi
          done
          cat env-vars.yaml

      - name: Upload env-vars.yaml
        uses: actions/upload-artifact@v4
        with:
          name: env-vars
          path: env-vars.yaml
  
  deploy:
    name: Deploy Cloud Run
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Authenticate GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Account
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          install_components: 'gke-gcloud-auth-plugin'

      - name: Download env-vars.yaml
        uses: actions/download-artifact@v4
        with:
          name: env-vars

      - name: Deploy Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --env-vars-file env-vars.yaml
